<?php

namespace Aternos\Rados\Constants;

enum AllocHintFlag: string implements EnumGetCValueInterface
{
    use EnumGetCValueTrait;
    use EnumFlagCombinationTrait;

    case SEQUENTIAL_WRITE = "LIBRADOS_ALLOC_HINT_FLAG_SEQUENTIAL_WRITE";
    case RANDOM_WRITE = "LIBRADOS_ALLOC_HINT_FLAG_RANDOM_WRITE";
    case SEQUENTIAL_READ = "LIBRADOS_ALLOC_HINT_FLAG_SEQUENTIAL_READ";
    case RANDOM_READ = "LIBRADOS_ALLOC_HINT_FLAG_RANDOM_READ";
    case APPEND_ONLY = "LIBRADOS_ALLOC_HINT_FLAG_APPEND_ONLY";
    case IMMUTABLE = "LIBRADOS_ALLOC_HINT_FLAG_IMMUTABLE";
    case SHORTLIVED = "LIBRADOS_ALLOC_HINT_FLAG_SHORTLIVED";
    case LONGLIVED = "LIBRADOS_ALLOC_HINT_FLAG_LONGLIVED";
    case COMPRESSIBLE = "LIBRADOS_ALLOC_HINT_FLAG_COMPRESSIBLE";
    case INCOMPRESSIBLE = "LIBRADOS_ALLOC_HINT_FLAG_INCOMPRESSIBLE";
}
