<?php

namespace Aternos\Rados\Constants;

enum OperationFlag: string implements EnumGetCValueInterface
{
    use EnumGetCValueTrait;
    use EnumFlagCombinationTrait;

    case NOFLAG = "LIBRADOS_OPERATION_NOFLAG";
    case BALANCE_READS = "LIBRADOS_OPERATION_BALANCE_READS";
    case LOCALIZE_READS = "LIBRADOS_OPERATION_LOCALIZE_READS";
    case ORDER_READS_WRITES = "LIBRADOS_OPERATION_ORDER_READS_WRITES";
    case IGNORE_CACHE = "LIBRADOS_OPERATION_IGNORE_CACHE";
    case SKIPRWLOCKS = "LIBRADOS_OPERATION_SKIPRWLOCKS";
    case IGNORE_OVERLAY = "LIBRADOS_OPERATION_IGNORE_OVERLAY";
    case FULL_TRY = "LIBRADOS_OPERATION_FULL_TRY";
    case FULL_FORCE = "LIBRADOS_OPERATION_FULL_FORCE";
    case IGNORE_REDIRECT = "LIBRADOS_OPERATION_IGNORE_REDIRECT";
    case ORDERSNAP = "LIBRADOS_OPERATION_ORDERSNAP";
    case RETURNVEC = "LIBRADOS_OPERATION_RETURNVEC";
}
