<?php

namespace Aternos\Rados\Constants;

enum OpFlag: string implements EnumGetCValueInterface
{
    use EnumGetCValueTrait;
    use EnumFlagCombinationTrait;

    case EXCL = "LIBRADOS_OP_FLAG_EXCL";
    case FAILOK = "LIBRADOS_OP_FLAG_FAILOK";
    case FADVISE_RANDOM = "LIBRADOS_OP_FLAG_FADVISE_RANDOM";
    case FADVISE_SEQUENTIAL = "LIBRADOS_OP_FLAG_FADVISE_SEQUENTIAL";
    case FADVISE_WILLNEED = "LIBRADOS_OP_FLAG_FADVISE_WILLNEED";
    case FADVISE_DONTNEED = "LIBRADOS_OP_FLAG_FADVISE_DONTNEED";
    case FADVISE_NOCACHE = "LIBRADOS_OP_FLAG_FADVISE_NOCACHE";
    case FADVISE_FUA = "LIBRADOS_OP_FLAG_FADVISE_FUA";
}
